### ISSUE TITLE
Structure of CBOR / COSE

### ISSUE THREAD

**Issue by stamo** [eu-digital-green-certificates/dgc-testdata#1]
I wanted to ask, can we use the structure of **CBOR** and **COSE** objects from the example in the Readme file as reference structure?

I mean that in the spec the CBOR structure is:
 
1        (iss) - bstr (2)
6        (iat) - bstr (2)
4        (exp) - bstr (2)
-260   (hcert) - map (5)

And in the example it is:

1        (iss) - text string (3)
6        (iat) - text string (3)
4        (exp) - text string (3)
-260   (hcert) - bstr (5)

Which is the right one?

Thank you in advance!

**Comment by stamo** [comment]
Thanks to the coleagues from Austria we have some test data to play with, but again I have a problem with the specification. I am afraid that we will have different implementations across the MS and they will not be interoperable.

![CoseStructure](https://user-images.githubusercontent.com/3283931/116776475-46283a80-aa71-11eb-898c-244477311f32.jpg)

Three problems on this screenshot:

1. It is common logic to have headers infront of payload and this is Austria's implementation (Unprotected is on index 1), but the spec says that **Unprotected** comes last (on index 3). This is not a MAP so we depend on indexes or we have to guess where to find useful info
2.  In the **Protected** there are two claims - **alg** and **kid**. No claim names in the specs. Austria's implementation is using 1 and 4 for claim names, but they are **Major CBOR types**. Again we have problem finding data, because this is a MAP and we are depending on names. Will it be **1 and 4** or **alg and kid**
3. And last but not least the Major CBOR type of **kid** can not be 4. 4 is an array of objects, while **kid** can be array of bytes or Base64Encoded string

**Comment by SchulzeStTSI** [comment]
@stamo 

Regarding point 1: The table referes to the COSE specification and has no explicit index in it. So it's as defined in the RFC "protected", "unprotected","payload" and "signature". (unprotected is in the bottom because empty and not used)

Regarding point 2: In the hCert Spec (https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md#33-cwt-claims) is alg and kid defined as "label 1 and label 4". This is defined in https://github.com/ehn-digital-green-development/COSE-JAVA/blob/master/src/main/java/COSE/HeaderKeys.java and then used in https://github.com/ehn-digital-green-development/hcert-kotlin/blob/main/src/main/kotlin/ehn/techiop/hcert/kotlin/chain/impl/FileBasedCryptoService.kt#L50, which is straight forward to the usage in the COSE JAVA Library itself: https://github.com/ehn-digital-green-development/COSE-JAVA/blob/master/src/main/java/COSE/Message.java#L118 . In the examples of the COSE is also this: https://tools.ietf.org/html/rfc8392#appendix-A.3, which defines also the 1/4 for alg and kid as label. Can you validate this to ensure, that we have the same understanding? "Major Type" should be here named as "Label". 

Regarding point 3: Yes, kid is defined as bstr (array), which is major type 2. 

Can you confirm me the points? Then i  create an pull request here: https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md to describe the open points more clear in this document.

**Comment by stamo** [comment]
@SchulzeStTSI 

Yes, I think it is OK, I have already changed my implementation to use 1 and 4 instead of alg and kid, so the name of the column should be changed to Label, or may be to Claim name to match the other table in the spec
