### ISSUE TITLE
DE: certificates have invalid kid

### ISSUE THREAD

**Issue by JChrist** [eu-digital-green-certificates/dgc-testdata#119]
As mentioned in the PR #117 , which unfortunately got merged. the certificates contain invalid `kid` and thus cannot be verified.

The kid contained in the certificate(s) is invalid/does not match the kid as calculated from the certificate provided in the test data.
In particular, for 1.json, the certificate contains kid (in base64 for easy reference): jt4zFtTaQYGB8HU6/8ajow==
The expected one - based on the CERTIFICATE field in the test data - would be: DEsVUSvpFAE=
The same error exists for other provided certificates as well.

@SchulzeStTSI all PRs are going to be merged without validation? What is the policy?

**Comment by lab-incert** [comment]
I confirm that I got the same issue while testing the DE certificates.

**Comment by SchulzeStTSI** [comment]
@JChrist Sry. I thought the comments were resolved. 
@SZoerner Please fix the kid issue.

**Comment by bhavin-qryptal** [comment]
[/DE/2DCode/raw/1.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/DE/2DCode/raw/1.json)
[/DE/2DCode/raw/1.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/DE/2DCode/raw/1.json)
[/DE/2DCode/raw/1.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/DE/2DCode/raw/1.json)

DGC Signing Certificates - DSCs are tagged with Unsupported Certificate Algorithm: RSASSA-PSS (oid=1.2.840.113549.1.1.10, name=RSASSA-PSS). This value should be ECDSA_WITH_SHA256 OR RSA_WITH_SHA256

@SZoerner and @SchulzeStTSI , If this is valid, please help fix OR ELSE guide me with expected behavior.

Thank you.

**Comment by bhavin-qryptal** [comment]
[DE/2DCode/raw/1.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/cce3001e358418ea2fe02f8fc1dba110916be4ae/DE/2DCode/raw/1.json)

dgc_expiry_date  datetime(2022, 5, 8, 10, 45, 40, tzinfo=datetime.timezone.utc)  is after dsc_not_valid_after  datetime(2022, 4, 30, 9, 31, 22, tzinfo=datetime.timezone.utc)

@SZoerner and @SchulzeStTSI , FYI and assistance.

Thank you.

**Comment by SZoerner** [comment]
@JChrist @lab-incert  Thank you for pointing out - I uploaded new content, now with the kid correctly calculated. May I ask you to retest?

**Comment by daniel-eder** [comment]
@SZoerner 1-2 pass the kid check now, 3 still fails, see https://github.com/eu-digital-green-certificates/dgc-testdata/actions/runs/884511158 (filterable html is attached as artifact) 

PS: If you create a PR the test verification script runs on it automatically and you'll see xfails (known issues that still fail) and xpasses (for known issues that no longer fail) as well as new issues that were potentially introduced. Right now there's an issue with the schema validation in the test script due to the schema url having changed on eHN but we're on that, and other issues are being tested correctly.

**Comment by JChrist** [comment]
hi @SZoerner, now the PNGs are working perfectly.
However, it seems that the PNGs are not matching the json test files.
For the json test data, the kid is correctly identified now, but the json test data contain an invalid `iat` field compared to the VALIDATIONCLOCK field
For example, for 1.json:
```
Certificate is NOT issued YET! now:2021-05-17 18:00:00.000Z iat:2021-05-27 15:21:38.000
```
